version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./tests:/tests

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
